name: publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - name: Run sandbox test
        run: npm run test:sandbox
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - run: npm publish
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
