name: publish
on: [push]
jobs:
  setup:
    - name: Check out repository code
      uses: actions/checkout@v2
  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']
    steps:
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --no-save
      - run: npm test
      - name: Run sandbox test
        run: npm run test:sandbox
        env:
          API_KEY: ${{ secrets.API_KEY }}
  publish:
    needs: test
    steps:
      - run: npm publish
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
