artifactVersion: 1.0.10
userAgent: uploader
invokerPackage: video.api.uploader.api
apiPackage: video.api.uploader
modelPackage: video.api.uploader.api.models
groupId: video.api
artifactDescription: api.video Android API video uploader
artifactUrl: https://github.com/apivideo/android-uploader
scmConnection: scm:git:git://github.com/apivideo/android-video-uploader.git
scmDeveloperConnection: scm:git:ssh://github.com:apivideo/android-video-uploader.git
scmUrl: https://github.com/apivideo/android-api-client
developerName: api.video ecosystem team
developerOrganization: api.video
developerOrganizationUrl: https://api.video
developerEmail: ecosystem@api.video
licenseName: MIT License
licenseUrl: http://www.opensource.org/licenses/mit-license.php
library: volley
dateLibrary: threetenbp
sourceFolder: src/main/java
artifactId: android-uploader
hideGenerationTimestamp: true
serializableModel: "true"
java8: "true"
gson: "true"
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  Environment.mustache:
    folder: src/main/java/video/api/uploader/api/models
    destinationFilename: Environment.java
  EmptyArrayFixTypeAdapterFactory.mustache:
    folder: src/main/java/video/api/uploader/api
    destinationFilename: EmptyArrayFixTypeAdapterFactory.java
  UploadChunkRequestBody.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: UploadChunkRequestBody.java
  ChunkFileInputStream.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: ChunkFileInputStream.java
  UploadProgressListener.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: UploadProgressListener.java
  UploadPartProgressListener.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: UploadPartProgressListener.java
  auth/apivideoauth.mustache:
    folder: src/main/java/video/api/uploader/api/auth
    destinationFilename: ApiVideoAuth.java
  README-uploader.mustache:
    destinationFilename: README.md
  post-generate-uploader.sh:
    destinationFilename: post-generate.sh
