changelog:
  - 1.3.6 (2024-04-25):
    - Add API to get rate limiting headers
  - 1.3.5 (2024-03-21):
    - Add missing proguard rules for gson and jackson
  - 1.3.4 (2024-01-08):
    - Upgrade dependencies, gradle and Kotlin
  - 1.3.3 (2023-12-14):
    - Add support for API level >= 34 for WorkManager
  - 1.3.2 (2023-09-26):
    - Extend Android minSdkVersion to 21
  - 1.3.1 (2023-08-22):
    - Fix cancellation of upload workers for the WorkManager API
  - 1.3.0 (2023-08-21):
    - Improve cancel of upload workers for the WorkManager API
  - 1.2.4 (2023-08-10):
    - Fix upload with upload token and video id when video is smaller than chunk size
  - 1.2.3 (2023-08-08):
    - Fix upload notification resources name
  - 1.2.2 (2023-04-20):
    - Add upload token and videoId in WorkManager tags
  - 1.2.1 (2023-04-04):
    - Add custom tag for WorkManager
    - Fix tag for progressive upload in WorkManager
    - Worker now returns the file in case developer want to delete it after upload.
    - Use api.video theme and icon for examples
  - 1.2.0 (2023-02-28):
    - Introduce WorkManager dedicated API
  - 1.1.2 (2022-11-16):
    - Fix the UploadService notification level
    - In example, add support for Android 13
  - 1.1.1 (2022-08-30):
    - Improve the upload Service
  - 1.1.0 (2022-08-22):
    - Add an upload Service
  - 1.0.0 (2022-07-05):
    - Add SDK origin header
  - 0.2.7 (2022-05-17):
    - Publicized chunk maxChunkSize
    - Add a progressive upload API to upload a specific part
  - 0.2.6 (2022-04-21):
    - Fix `video.publishedAt` type
  - 0.2.5 (2022-03-17):
    - Fix metadata query param in GET /videos
  - 0.2.4 (2022-03-10):
    - Add Origin identification headers
  - 0.2.3 (2022-01-24):
    - Add applicationName parameter (to allow user agent extension)
  - 0.2.2 (2022-01-06):
    - Increase chunked and progressive upload speed
    - Update min Sdk version to Android API 24
  - 0.2.1 (2021-12-13):
    - Add an interface for progressive upload session
  - 0.2.0 (2021-12-06):
    - Add `name` attribute in player themes
  - 0.1.1 (2021-11-19):
    - Simplify VideosApi() constructor
    - Publish AAR instead of JAR

originClient: android-uploader
invokerPackage: video.api.uploader.api
apiPackage: video.api.uploader
modelPackage: video.api.uploader.api.models
groupId: video.api
gitRepoId: api.video-android-uploader
artifactDescription: The official Android api.video uploader
artifactUrl: https://github.com/apivideo/api.video-android-uploader
scmConnection: scm:git:git://github.com/apivideo/api.video-android-uploader.git
scmDeveloperConnection: scm:git:ssh://github.com:apivideo/api.video-android-uploader.git
scmUrl: https://github.com/apivideo/api.video-android-uploader
developerName: api.video ecosystem team
developerOrganization: api.video
developerOrganizationUrl: https://api.video
developerEmail: ecosystem@api.video
licenseName: MIT License
licenseUrl: http://www.opensource.org/licenses/mit-license.php
library: okhttp-gson
dateLibrary: threetenbp
artifactId: android-video-uploader
hideGenerationTimestamp: true
serializableModel: "true"
java8: "true"
android: "true"
uploader: "true"
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  Nullable.mustache:
    folder: src/main/java/video/api/uploader/api/models
    destinationFilename: Nullable.java
  DeepObject.mustache:
    folder: src/main/java/video/api/uploader/api/models
    destinationFilename: DeepObject.java
  Environment.mustache:
    folder: src/main/java/video/api/uploader/api/models
    destinationFilename: Environment.java
  ApiVideoAuthInterceptor.mustache:
    folder: src/main/java/video/api/uploader/api/auth
    destinationFilename: ApiVideoAuthInterceptor.java
  EmptyArrayFixTypeAdapterFactory.mustache:
    folder: src/main/java/video/api/uploader/api
    destinationFilename: EmptyArrayFixTypeAdapterFactory.java
  IProgressiveUploadSession.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: IProgressiveUploadSession.java
  UploadChunkRequestBody.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: UploadChunkRequestBody.java
  UploadProgressListener.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: UploadProgressListener.java
  UploadPartProgressListener.mustache:
    folder: src/main/java/video/api/uploader/api/upload
    destinationFilename: UploadPartProgressListener.java
  post-generate-android-uploader.sh:
    destinationFilename: post-generate.sh
  maven-push.gradle.mustache:
    destinationFilename: maven-push.gradle
  android/notifications/NotificationExtensions.mustache:
    folder: src/main/java/video/api/uploader/api/notifications
    destinationFilename: NotificationExtensions.kt
  android/notifications/NotificationUtils.mustache:
    folder: src/main/java/video/api/uploader/api/notifications
    destinationFilename: NotificationUtils.kt
  android/services/Extensions.mustache:
    folder: src/main/java/video/api/uploader/api/services
    destinationFilename: Extensions.kt
  android/services/ServiceNotificationUtils.mustache:
    folder: src/main/java/video/api/uploader/api/services
    destinationFilename: ServiceNotificationUtils.kt
  android/services/UploadService.mustache:
    folder: src/main/java/video/api/uploader/api/services
    destinationFilename: UploadService.kt
  android/services/UploadServiceListener.mustache:
    folder: src/main/java/video/api/uploader/api/services
    destinationFilename: UploadServiceListener.kt
  android/services/UploadTask.mustache:
    folder: src/main/java/video/api/uploader/api/services
    destinationFilename: UploadTask.kt
  android/work/stores/NotificationConfigurationStore.mustache:
    folder: src/main/java/video/api/uploader/api/work/stores
    destinationFilename: NotificationConfigurationStore.kt
  android/work/stores/ProgressiveUploadSessionStore.mustache:
    folder: src/main/java/video/api/uploader/api/work/stores
    destinationFilename: ProgressiveUploadSessionStore.kt
  android/work/stores/VideosApiStore.mustache:
    folder: src/main/java/video/api/uploader/api/work/stores
    destinationFilename: VideosApiStore.kt
  android/work/workers/AbstractUploadWorker.mustache:
    folder: src/main/java/video/api/uploader/api/work/workers
    destinationFilename: AbstractUploadWorker.kt
  android/work/workers/ProgressiveUploadWorker.mustache:
    folder: src/main/java/video/api/uploader/api/work/workers
    destinationFilename: ProgressiveUploadWorker.kt
  android/work/workers/UploadWorker.mustache:
    folder: src/main/java/video/api/uploader/api/work/workers
    destinationFilename: UploadWorker.kt
  android/work/OperationWithRequest.mustache:
    folder: src/main/java/video/api/uploader/api/work
    destinationFilename: OperationWithRequest.kt
  android/work/UploadWorkerHelper.mustache:
    folder: src/main/java/video/api/uploader/api/work
    destinationFilename: UploadWorkerHelper.kt
  android/work/WorkManagerExtensions.mustache:
    folder: src/main/java/video/api/uploader/api/work
    destinationFilename: WorkManagerExtensions.kt
  android/work/DataExtensions.mustache:
    folder: src/main/java/video/api/uploader/api/work
    destinationFilename: DataExtensions.kt
  android/work/utils/Hash.mustache:
    folder: src/main/java/video/api/uploader/api/work/utils
    destinationFilename: Hash.kt
  consumer-rules.mustache:
    destinationFilename: consumer-rules.pro
