artifactVersion: 1.0.0
licenseName: MIT
sourceFolder: src/
groupId: video.api
artifactDescription: api.video csharp API client
artifactId: csharp-api-client
developerName: api.video ecosystem team
developerOrganization: api.video
developerOrganizationUrl: https://api.video
developerEmail: ecosystem@api.video
packageName: ApiVideo
artifactUrl: https://github.com/apivideo/csharp-api-client
gitRepoId: api.video-csharp-client
targetFramework: v4.5.2
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  page.mustache:
    folder: src/ApiVideo/Model
    destinationFilename: Page.cs
  pagination.md.mustache:
    folder: docs
    destinationFilename: Pagination.md
  ApiVideoClient.mustache:
    folder: src/ApiVideo/
    destinationFilename: ApiVideo.cs
  AuthenticationManager.mustache:
    folder: src/ApiVideo/Client/
    destinationFilename: AuthenticationManager.cs
  EmptyArrayFixTypeConverter.mustache:
    folder: src/ApiVideo/Client/
    destinationFilename: EmptyArrayFixTypeConverter.cs
  IUploadProgressListener.mustache:
    folder: src/ApiVideo/Model
    destinationFilename: IUploadProgressListener.cs
  IUploadPartProgressListener.mustache:
    folder: src/ApiVideo/Model
    destinationFilename: IUploadPartProgressListener.cs
  post-generate.sh:
    destinationFilename: post-generate.sh