npmName: "@api.video/nodejs-client"
npmVersion: 2.0.0
npmDescription: api.video typescript client
npmAuthor: api.video ecosystem team

httpUserAgent: @api.video/client (GO; v:2.0.0; )
licenseName: MIT

templateDir: typescript
# Defines the output folder for each kind of specific templates.
# The naming is quite confusing because it was based on java "package" naming,
# but this can in fact be used just as a "path".
modelPackage: src/model
apiPackage: src/api
testPackage: test
#apiTestFileFolder:
#modelTestFileFolder:
#docPackage: doc/
apiDocFileFolder: doc/api
modelDocFileFolder: doc/model

ignoredFiles:
  # This shouldn't be needed.
  # These files should be automatically excluded from supporting files since they are configured in files.
  - doc/api/api_doc.md.mustache
  - doc/model/model_doc.md.mustache
  - src/api/api.ts.mustache
  - src/model/model.ts.mustache

# `templateType` can be any of the following:
# API Model APIDocs ModelDocs APITests ModelTests SupportingFiles
files:
  doc/api/api_doc.md.mustache:
    templateType: APIDocs
  doc/model/model_doc.md.mustache:
    templateType: ModelDocs
  src/api/api.ts.mustache:
    templateType: API
  src/model/model.ts.mustache:
    templateType: Model
