name: Get profiles
description: Get available client profile names
outputs:
  profiles:
    description: The list of available profiles as a Json array string
    value: ${{ steps.get-profiles.outputs.profiles }}
runs:
  using: composite
  steps:
    - id: get-profiles
      run: |
        res=""
        for file in config/*
        do
            if [[ -f $file ]]; then
                res+="{'name': '"`echo $file  | sed -n 's/.*\/\([^/]*\)\.yaml/\1/p'`"', 'repository': '"`sed -ne "s/gitRepoId: \([^']*\)/\1/p" $file`"'},"
            fi
        done
        echo "::set-output name=profiles::["`echo $res | sed 's/.$//'`"]"
      shell: bash